### ISSUE TITLE
AttributeError: 'Page' object has no attribute 'get_text'

### ISSUE THREAD

**Issue by keidododo** [flaribbit/paper-translator#2]
正在提取文本
Traceback (most recent call last):
  File "main.py", line 90, in <module>
    main()
  File "main.py", line 59, in main
    text = read_pdf(args.file)
  File "main.py", line 16, in read_pdf
    blocks = page.get_text("blocks")
AttributeError: 'Page' object has no attribute 'get_text'

**Comment by flaribbit** [comment]
感谢反馈，对于这个问题，我能想到三种原因
1. 输入的文件不是 pdf 或者 txt（尽管扩展名符合）。
2. 依赖版本，尝试 `pip install -U pymupdf`，我这里版本 `1.19.6` 没问题
3. pdf 是纯图片/扫描版，里面没有文本。本程序尚未考虑这种情况，但我用扫描版 pdf 也无法复现。
